server:
    port: 8085
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/2ndweekproject
        username: root
        password: 12341234
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy : ant_path_matcher
logging:
    config: classpath:logback-spring-local.xml
    level:
        org.springframework.security: DEBUG
