server:
    port: 8085
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/2ndweekproject
        username: root
        password: 12341234
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy : ant_path_matcher
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate.format_sql: true
    profiles:
        active: aws


logging:
    config: classpath:logback-spring-local.xml
    level:
        org.springframework.security: DEBUG

